# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'people'},
        ),
        migrations.RemoveField(
            model_name='persontoevent',
            name='hashtags',
        ),
        migrations.AddField(
            model_name='person',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='person_set', to='people.Hashtag', verbose_name='해시태그'),
        ),
    ]
