# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20170827_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.CharField(max_length=20, verbose_name='이름'),
        ),
    ]
